classDiagram
    class Loan {
        - id
        - book
        - user
        - dueData
        - retriveDate
        - loanDate
        + loan(book, user, dueDate, retriveDate, loanDate)
        + renew(newDuaDate)
        + return()
        + isOverDue()
    }
    class Notification {
        <<interface>>
        + notify(Loan)
    }

    class EmailNotifier {
        + notify(loan)
    }


    Loan --> Notification : usa
    EmailNotifier ..|> Notification : implementa